---
title: "Reproducible Document"
author: "Oliver Bonde van Zwol"
format: html
---

```{r setup}
#| message: false
#| warning: false

library("tidyverse")

post_meal_data <- read.csv2(here::here("data/post-meal-insulin.csv"))
```

## About me

-   Oliver
-   PhD

Just started on a **PhD** at *FGM*

## Simple code

```{r}
3 * 3
```




## Writing R code

2+2

```{r}
2 + 2
```

## Testing for Git

It is really cold outside


## Showing the data

```{r}
post_meal_data

glimpse(post_meal_data)
```

## Plot one continous variable

```{r}
#| fig-cap: "Distribution of BMI."
#| label: fig-bmi-histo
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```

See @fig-bmi-histo


## Exercise: discrete plots

```{r}
#| fig-cap: "Groups"
#| label: fig-group-bar
ggplot(post_meal_data, aes(x = Group)) +
  geom_bar()
```

See @fig-group-bar above for a cool plot!

## Plotting two discrete variables

```{r}
ggplot(post_meal_data, aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())
```


## Side by side plot
```{r fig-bmi-glycemia}
#| fig-cap: "BMI and glycemia, side by side"
#| fig-subcap:
#|   - "Distribution of BMI."
#|   - "Number of those with glycemia."
#| layout-ncol: 2
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```

## Plotting two continuous variables

```{r}
#| fig-cap: "Scatterplot of BMI and the area under the curve for glucose"
#| label: fig-bmi-auc-pg
ggplot(post_meal_data, aes(x = BMI, y = auc_pg)) +
  geom_point() +
  geom_smooth()
```
